VERSION = "2.0.0"

[DOCUMENTATION]
ORG_NAME = "Carrier Inspiration Ministries"
ORG_URL = "https://cimco.github.io"
ORG_DESCRIPTION = "CIMCO (Carrier Inspiration Ministries Coin) is a market-facing token designed to pump value into PNEUMA for global Kingdom impact."

[[CURRENCIES]]
code = "CIMCO"
issuer = "GARWXOINWTEWUU4JH3XCDGIDNAYXEILOOKSKZDVOUM6WRC4FO7XM3SKP"
display_decimals = 7
image = "https://cimco.github.io/CIMCO-logo.png"
desc = "CIMCO is the market-entry token for the Project PNEUMA economy. It draws in value from global markets and redirects it into gospel work via the VESSEL app."
conditions = "Publicly tradable. Used as the only gateway into PNEUMA. Supported within the VESSEL wallet ecosystem."
status = "live"